export const RECEIVE_USERS = 'RECEIVE_USERS';
export const SAVE_USER_ANSWER = 'SAVE_USER_ANSWER'
export const SAVE_USER_QUESTION ='SAVE_USER_QUESTION'


export const SET_AUTH_USER = 'SET_AUTH_USER';


export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER'
export const CREATE_QUESTION = 'CREATE_QUESTION'

